### ISSUE TITLE
Docs TODO list

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/docs-redux#7]
All of these would be very nice to have:

- [ ] generate component documentation directly from the `idyll-components` module
- [ ] figure out a story for versioning the documentation
- [ ] basic blog post template for announcements, etc.
- [ ] move this repo back to `idyll-lang/idyll`
- [ ] add more examples to gallery
- [ ] iframe in examples in gallery so we can overlay links to the source, etc.
- [ ] syntax highlighting
